Merge with DRfC
aws-deepracer-community/deepracer-for-dummies pull request #47
Opened 2020-10-03 14:04 UTC by larsll

2020-10-05 16:17 UTC, jochem725 commented on README.md
> +DeepRacer-For-Cloud (DRfC) started as an extension of the work done by Alex (https://github.com/alexschultz/deepracer-for-dummies), which is again a wrapper around the amazing work done by Chris (htt
Should we also move the deepracer-build repo to the community?

2020-10-05 16:17 UTC, jochem725 commented on README.md
> +Main differences to the work done by Alex is:
Is this part still relevant (since most of Alex' work will now be overwritten and deepracer-for-dummies will be harder to use as reference).

2020-10-05 17:49 UTC, larsll commented on README.md
> +DeepRacer-For-Cloud (DRfC) started as an extension of the work done by Alex (https://github.com/alexschultz/deepracer-for-dummies), which is again a wrapper around the amazing work done by Chris (htt
Yes - this is definitively an option. It would fit on top of the deepracer repository (as the 'raw' edition of it all). Also that repository is out of date.

2020-10-05 17:52 UTC, larsll commented on README.md
> +Main differences to the work done by Alex is:
I think the README will require a full rewrite.

2021-01-23 22:50 UTC, breadcentric requested changes
Before merging we should update the readme and make a plan on which larsll/ urls we need to update to make it all work after the merge

2021-01-23 22:50 UTC, breadcentric commented on README.md
> +Main differences to the work done by Alex is:
Let's make sure we do this before we merge

2021-01-23 22:50 UTC, breadcentric commented on README.md
> +Full documentation can be found on the [Deepracer-for-Cloud GitHub Pages](https://larsll.github.io/deepracer-for-cloud).
Point at the community repo

2021-01-23 22:50 UTC, breadcentric commented on bin/activate.sh
> +COACH_VER=$(docker inspect larsll/deepracer-rlcoach:$DR_COACH_IMAGE | jq -r .[].Config.Labels.version)
Should we be pushing to community repos?

2021-01-23 22:50 UTC, breadcentric commented on bin/init.sh
> +docker pull larsll/deepracer-rlcoach:$COACH_VERSION
Should we be pushing to community repos?

2021-01-23 22:50 UTC, breadcentric commented on docker/docker-compose-eval.yml
> +    image: larsll/deepracer-rlcoach:${DR_COACH_IMAGE}
Should we be pushing to community repos?

2021-01-23 22:50 UTC, breadcentric commented on docker/docker-compose-training.yml
> +    image: larsll/deepracer-rlcoach:${DR_COACH_IMAGE}
Should we be pushing to community repos?

2021-01-23 22:50 UTC, breadcentric commented on docs/index.md
> +DeepRacer-For-Cloud (DRfC) started as an extension of the work done by Alex (https://github.com/alexschultz/deepracer-for-dummies), which is again a wrapper around the amazing work done by Chris (htt
move deepracer-build to community repos

2021-01-23 22:50 UTC, breadcentric commented on docs/installation.md
> +	git clone https://github.com/larsll/deepracer-for-cloud.git
Update to community repo

2021-01-23 22:50 UTC, breadcentric commented on scripts/log-analysis/start.sh
> + larsll/deepracer-loganalysis:v2-cpu
Update to community repo

2021-01-23 22:50 UTC, breadcentric commented on utils/sample-createspot.sh
> +    su -c 'git clone https://github.com/larsll/deepracer-for-cloud.git && echo "$S3_LOCATION/node-config" > /home/ubuntu/deepracer-for-cloud/autorun.s3url && /home/ubuntu/deepracer-for-cloud/bin/prep
Update to community repo

2021-01-24 15:13 UTC, larsll commented on README.md
> +Full documentation can be found on the [Deepracer-for-Cloud GitHub Pages](https://larsll.github.io/deepracer-for-cloud).
Fixed

2021-01-24 15:13 UTC, larsll commented on bin/activate.sh
> +COACH_VER=$(docker inspect larsll/deepracer-rlcoach:$DR_COACH_IMAGE | jq -r .[].Config.Labels.version)
Fixed

2021-01-24 15:13 UTC, larsll commented on bin/init.sh
> +docker pull larsll/deepracer-rlcoach:$COACH_VERSION
Fixed

2021-01-24 15:13 UTC, larsll commented on docker/docker-compose-training.yml
> +    image: larsll/deepracer-rlcoach:${DR_COACH_IMAGE}
Fixed

2021-01-24 15:14 UTC, larsll commented on docker/docker-compose-eval.yml
> +    image: larsll/deepracer-rlcoach:${DR_COACH_IMAGE}
Fixed

2021-01-24 15:14 UTC, larsll commented on docs/index.md
> +DeepRacer-For-Cloud (DRfC) started as an extension of the work done by Alex (https://github.com/alexschultz/deepracer-for-dummies), which is again a wrapper around the amazing work done by Chris (htt
This is in progress here https://github.com/aws-deepracer-community/deepracer/pull/102

2021-01-24 15:14 UTC, larsll commented on docs/installation.md
> +	git clone https://github.com/larsll/deepracer-for-cloud.git
Done

2021-01-24 15:14 UTC, larsll commented on utils/sample-createspot.sh
> +    su -c 'git clone https://github.com/larsll/deepracer-for-cloud.git && echo "$S3_LOCATION/node-config" > /home/ubuntu/deepracer-for-cloud/autorun.s3url && /home/ubuntu/deepracer-for-cloud/bin/prep
Done

2021-01-24 15:15 UTC, larsll commented on scripts/log-analysis/start.sh
> + larsll/deepracer-loganalysis:v2-cpu
This should be opened as an issue, as it would need to use the community log-analysis image (why use two)?

2021-01-24 15:41 UTC, breadcentric approved these changes

2021-01-24 15:42 UTC, merged